apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentmang-app
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentmang-app
  template:
    metadata:
      labels:
        app: studentmang-app
    spec:
      containers:
        - name: studentmang-app
          image: maramsd/studentmang-app:latest   # Ton image dockerhub
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: NodePort
